[[plugins]]
package = "netlify-plugin-cypress"
  # let's run tests against the built site
  [plugins.inputs]
    record = true
  [plugins.inputs.postBuild]
    enable = true
    
[build.environment]
GATSBY_BRANCH = "main"
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[redirects]]
from = "/docs/*"
to = "https://rudderstack-docs-to-proxy.netlify.app/:splat"
status = 200 

[[redirects]]
from = "/docs-assets/*"
to = "https://rudderstack-docs-to-proxy.netlify.app/:splat"
status = 200 

[[redirects]]
from = "/docs/get-started/installing-and-setting-up-rudderstack/docker"
to = "/docs/rudderstack-open-source/installing-and-setting-up-rudderstack/docker/"
status = 301 
[[redirects]]
from = "/docs/rudderstack-api/user-suppression/"
to = "/docs/rudderstack-api/data-regulation-api/"
status = 301 
[[redirects]]
from = "/docs/get-started/installing-and-setting-up-rudderstack/developer-machine-setup/"
to = "/docs/rudderstack-open-source/installing-and-setting-up-rudderstack/developer-machine-setup/"
status = 301 
from = "/docs/connections/adding-source-and-destination-rudderstack/"
to = "/docs/rudderstack-cloud/destinations/"
status = 301 
[[redirects]]
from = "/docs/connections/rudderstack-connection-modes/"
to = "/docs/rudderstack-cloud/rudderstack-connection-modes/"
status = 301 
[[redirects]]
from = "/docs/get-started/rudderstack-connection-modes"
to = "/docs/connections/rudderstack-connection-modes/"
status = 301 
