[build.environment]
GATSBY_BRANCH = "main"
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[redirects]]
from = "/docs/get-started/installing-and-setting-up-rudderstack/docker"
to = "https://www.rudderstack.com/docs/rudderstack-open-source/installing-and-setting-up-rudderstack/docker/"
status = 301 
[[redirects]]
from = "/docs/rudderstack-api/user-suppression/"
to = "https://rudderstack.com/docs/rudderstack-api/data-regulation-api/"
status = 301 


