[build.environment]
GATSBY_BRANCH = "main"
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[redirects]]
from = "/docs/get-started/installing-and-setting-up-rudderstack/docker"
to = "/docs/rudderstack-open-source/installing-and-setting-up-rudderstack/docker/"
status = 301 
[[redirects]]
from = "/docs/rudderstack-api/user-suppression/"
to = "/docs/rudderstack-api/data-regulation-api/"
status = 301 
[[redirects]]
from = "/docs/get-started/installing-and-setting-up-rudderstack/developer-machine-setup/"
to = "/docs/rudderstack-open-source/installing-and-setting-up-rudderstack/developer-machine-setup/"
status = 301 
[[redirects]]
from = "/docs/connections/adding-source-and-destination-rudderstack/"
to = "/docs/rudderstack-cloud/destinations/"
status = 301 
[[redirects]]
from = "/docs/connections/rudderstack-connection-modes/"
to = "/docs/rudderstack-cloud/rudderstack-connection-modes/"
status = 301 
[[redirects]]
from = "/docs/get-started/rudderstack-connection-modes"
to = "/docs/connections/rudderstack-connection-modes/"
status = 301 
