[build.environment]
GATSBY_BRANCH = "main"
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[redirects]]
from = "/get-started/installing-and-setting-up-rudderstack/docker"
to = "/rudderstack-open-source/installing-and-setting-up-rudderstack/docker/"
status = 301 
[[redirects]]
from = "/rudderstack-api/user-suppression/"
to = "/rudderstack-api/data-regulation-api/"
status = 301 
[[redirects]]
from = "/get-started/installing-and-setting-up-rudderstack/developer-machine-setup/"
to = "/rudderstack-open-source/installing-and-setting-up-rudderstack/developer-machine-setup/"
status = 301 
[[redirects]]
from = "/connections/adding-source-and-destination-rudderstack/"
to = "/rudderstack-cloud/destinations/"
status = 301 
[[redirects]]
from = "/connections/rudderstack-connection-modes/"
to = "/rudderstack-cloud/rudderstack-connection-modes/"
status = 301 
[[redirects]]
from = "/get-started/rudderstack-connection-modes"
to = "/connections/rudderstack-connection-modes/"
status = 301 
[[redirects]]
from = "/get-started/installing-and-setting-up-rudderstack/kubernetes"
to = "/rudderstack-open-source/installing-and-setting-up-rudderstack/kubernetes/"
status = 301 
[[redirects]]
from = "/integration/amazon-personalize/"
to = "/integration/amazon-personalize/"
status = 301 
[[redirects]]
from = "/destinations/hotjar/"
to = "/destinations/analytics/hotjar/"
status = 301 
[[redirects]]
from = "/cloud-extract-sources/auth0/"
to = "/stream-sources/auth0/"
status = 301 
[[redirects]]
from = "/rudderstack-api/rudderstack-spec/common-fields/"
to = "/rudderstack-api/api-specification/rudderstack-spec/common-fields/"
status = 301 
[[redirects]]
from = "/warehouse-actions/google-bigquery/"
to = "/reverse-etl/google-bigquery/"
status = 301 
[[redirects]]
from = "/warehouse-actions/postgresql/"
to = "/reverse-etl/postgresql/"
status = 301 
[[redirects]]
from = "/rudderstack-sdk-integration-guides/rudderstack-go-sdk/"
to = "/stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk/"
status = 301 
[[redirects]]
from = "/warehouse-actions/snowflake/"
to = "/reverse-etl/snowflake/"
status = 301 
[[redirects]]
from = "/warehouse-actions/features/"
to = "/reverse-etl/features/"
status = 301 
[[redirects]]
from = "/warehouse-actions/features/airflow-provider/"
to = "/reverse-etl/features/airflow-provider/"
status = 301 
[[redirects]]
from = "/warehouse-actions/features/models/"
to = "/reverse-etl/features/models/"
status = 301 
[[redirects]]
from = "/warehouse-actions/features/visual-data-mapper/"
to = "/reverse-etl/features/visual-data-mapper/"
status = 301 
[[redirects]]
from = "/warehouse-actions/common-settings/"
to = "/reverse-etl/common-settings/"
status = 301 
[[redirects]]
from = "/warehouse-actions/common-settings/sync-schedule-settings/"
to = "/reverse-etl/common-settings/sync-schedule-settings/"
status = 301 
[[redirects]]
from = "/warehouse-actions/common-settings/sync-modes/"
to = "/reverse-etl/common-settings/sync-modes/"
status = 301 
[[redirects]]
from = "/warehouse-actions/common-settings/importing-data-using-models/"
to = "/reverse-etl/common-settings/importing-data-using-models/"
status = 301 
[[redirects]]
from = "/warehouse-actions/common-settings/importing-data-using-tables/"
to = "/reverse-etl/common-settings/importing-data-using-tables/"
status = 301 
[[redirects]]
from = "/warehouse-actions/faq/"
to = "/reverse-etl/faq/"
status = 301 
[[redirects]]
from = "/warehouse-actions/amazon-redshift/"
to = "/reverse-etl/amazon-redshift/"
status = 301 
[[redirects]]
from = "/warehouse-actions/"
to = "/reverse-etl/"
status = 301 
[[redirects]]
from = "/warehouse-actions/amazon-s3/"
to = "/reverse-etl/amazon-s3/"
status = 301 
[[redirects]]
from = "/warehouse-actions/clickhouse/"
to = "/reverse-etl/clickhouse/"
status = 301 
[[redirects]]
from = "/installing-and-setting-up-rudderstack/native-installation/"
to = "/get-started/installing-and-setting-up-rudderstack/"
status = 301 
[[redirects]]
from = "/destinations/marketing/qualtrics-website-feedback"
to = "/integration/qualtrics-website-feedback/"
status = 301 
[[redirects]]
from = "/destinations/aws-personalize"
to = "/integration/amazon-personalize/"
status = 301 
[[redirects]]
from = "/integration/qualtrics-website-feedback/"
to = "/integration/qualtrics-website-feedback/"
status = 301 
[[redirects]]
from = "/contributors-guide/create-a-new-destination-transformer-for-rudder/best-practices-for-coding-transformation-functions-in-javascript/"
to = "/user-guides/how-to-guides/create-a-new-destination-transformer-for-rudder/best-practices-for-coding-transformation-functions-in-javascript/"
status = 301 
[[redirects]]
from = "/destinations/salesforce/"
to = "/integration/salesforce/"
status = 301 
[[redirects]]
from = "/contributors-guide/developing-integrations-for-rudderstack/"
to = "/user-guides/how-to-guides/developing-integrations-for-rudderstack/"
status = 301 
[[redirects]]
from = "/contributors-guide/implement-native-js-sdk-integration"
to = "/user-guides/how-to-guides/implement-native-js-sdk-integration/"
status = 301 
[[redirects]]
from = "/destinations/branchio/"
to = "/destinations/attribution/branchio/"
status = 301 
[[redirects]]
from = "/user-guides/data-warehouse-integrations/warehouse-schemas/"
to = "/data-warehouse-integrations/warehouse-schemas/"
status = 301 
[[redirects]]
from = "/how-to-guides/adding-source-and-destination-rudderstack/"
to = "/connections/adding-source-and-destination-rudderstack/"
status = 301 
[[redirects]]
from = "/rudderstack-sdk-integration-guides"
to = "/stream-sources/rudderstack-sdk-integration-guides/"
status = 301 
[[redirects]]
from = "/adding-a-new-user-transformation-in-rudderstack/"
to = "/"
status = 301 
[[redirects]]
from = "/administrators-guide/alerting"
to = "/user-guides/administrators-guide/alerting/"
status = 301 
[[redirects]]
from = "/integration/minio/"
to = "/integration/minio/"
status = 301 
[[redirects]]
from = "/destinations/data-ingestion/connections/adding-source-and-destination-rudderstack/"
to = "/connections/adding-source-and-destination-rudderstack/"
status = 301 
[[redirects]]
from = "/user-guides/administrators-guides/"
to = "/user-guides/administrators-guide/"
status = 301 
[[redirects]]
from = "/rudderstack-enterprise/user-suppression/"
to = "/rudderstack-api/user-suppression/"
status = 301 
[[redirects]]
from = "/rudderstack-api-spec/rudderstack-ecommerce-events-specification/"
to = "/rudderstack-api/api-specification/rudderstack-ecommerce-events-specification/"
status = 301 
[[redirects]]
from = "/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk"
to = "/stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/"
status = 301 
[[redirects]]
from = "/data-warehouse-integration-guides/snowflake/"
to = "/data-warehouse-integrations/snowflake/"
status = 301 
[[redirects]]
from = "/getting-started/installing-and-setting-up-rudderstack/developer-machine-setup"
to = "/get-started/installing-and-setting-up-rudderstack/developer-machine-setup/"
status = 301 
[[redirects]]
from = "/user-guides/how-to-guides/dynamic-destination-config/"
to = "/destinations/webhooks/"
status = 301 
[[redirects]]
from = "/get-started/live-events"
to = "/rudderstack-cloud/live-events"
status = 301 
[[redirects]]
from = "/glossary"
to = "/get-started/glossary"
status = 301 
[[redirects]]
from = "/connections/models/"
to = "/reverse-etl/features/models/"
status = 301 
[[redirects]]
from = "/sources/appsflyer"
to = "/stream-sources/appsflyer/"
status = 301 
[[redirects]]
from = "/destinations/marketing/qualtrics-website-feedback/"
to = "/integration/qualtrics-website-feedback/"
status = 301 
[[redirects]]
from = "/stream-sources/rudderstack-event-streams/customerio/"
to = "/destinations/marketing/customer.io/"
status = 301 
[[redirects]]
from = "/destinations/minio/"
to = "/integration/minio/"
status = 301 
[[redirects]]
from = "/rudderstack-warehouse-actions/amazon-redshift/"
to = "/data-warehouse-integrations/amazon-redshift/"
status = 301 